name: Android PR & Build CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Ktlint
        run: ./gradlew ktlintCheck

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Generate Dokka Documentation
        run:  ./gradlew :WeatherSDK:dokkaGeneratePublicationHtml

      - name: Upload Dokka Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dokka-documentation
          path: WeatherSDK/build/dokkaDir

  connected-tests:
    needs: setup

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'gradle'

      - name: Cache build artifacts
        uses: ./.github/actions/cache-build-paths
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Save logcat output
        run: adb logcat > logcat.txt &

      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 35
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          ram-size: 2G
          disk-size: 10G
          force-avd-creation: false
          emulator-options: -no-snapshot -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            chmod +x .github/workflows/script/run_tests.sh
            .github/workflows/script/run_tests.sh

      - name: Upload failed tests screenshots
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: screenshots
          path: Screenshots

      - name: Upload logcat output
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: logcat
          path: logcat.txt

  build:
    needs: test-and-lint
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Extract Version Name
        run: |
          VERSION_NAME=$(./gradlew -q app:properties | grep "versionName:" | awk '{print $2}' | tr -d '\r')
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk-${{ env.VERSION_NAME }}
          path: app/build/outputs/apk/release/*.apk
