name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Grant execute permission to Gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Build release APK
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # Extract Version Name from Gradle
      - name: Extract Version Name
        run: |
          VERSION_NAME=$(./gradlew -q app:properties | grep "versionName:" | awk '{print $2}' | tr -d '\r')
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      # Upload the APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk-${{ env.VERSION_NAME }}
          path: app/build/outputs/apk/release/*.apk
